pluginGroup=com.lucashyuan
pluginName=Darcula Veil
pluginVersion=0.4.0

platformLocalPath=C:/Program Files/JetBrains/JetBrains Rider 2024.3.6
pluginSinceBuild=262

jvmTargetVersion=25

org.gradle.jvmargs=-Xmx3072m
org.gradle.caching=true
org.gradle.configuration-cache=false
kotlin.stdlib.default.dependency=false
